name: ManiaCore
version: ${project.version}
main: net.hungermania.enforcer.EnforcerSpigot
authors: [ Firestar311 ]
description: Punishments Plugin
website: hungermania.net
depend: [ TimoCloud,LuckPerms,Vault,ManiaCore ]
commands:
  ban:
  tempban:
  mute:
  tempmute:
  warn:
  kick:
  ipban:
  ipmute:
  rules: #Maybe
  mrules: #Maybe