name: ManiaHub
version: ${project.version}
main: net.hungermania.hub.ManiaHub
description: HungerMania's Hub
depend: [ManiaCore]
commands:
    testadmin:
    spawn:
    fly:
    hologram:
    leaderboard:
    npc: