package net.hungermania.maniacore.api.region;

public enum FlagType {
    BUILD, INTERACT, BLOCK_BREAK, BLOCK_PLACE, USE, DAMAGE_ANIMALS, CHEST_ACCESS, RIDE, PVP, SLEEP, TNT, VEHICLE_PLACE, VEHICLE_DESTROY, LIGHTER, BLOCK_TRAMPLING, FROSTED_ICE_FORM, CREEPER_EXPLOSION, ENDERDRAGON_BLOCK_DAMAGE, GHAST_FIREBALL, OTHER_EXPLOSION, FIRE_SPREAD, ENDERMAN_GRIEF, SNOWMAN_TRAILS, MOB_DAMAGE, MOB_SPAWNING, DENY_SPAWN, ENTITY_PAINTING_DESTROY, ENTITY_ITEM_FRAME_DESTROY, WITHER_DAMAGE, LAVA_FIRE, LIGHTNING, WATER_FLOW, LAVA_FLOW, SNOW_FALL, SNOW_MELT, ICE_FORM, ICE_MELT, FROSTED_ICE_MELT, MUSHROOM_GROWTH, LEAF_DECAY, GRASS_GROWTH, MYCELIUM_SPREAD, VINE_GROWTH, CROP_GROWTH, SOIL_DRY, ENTRY, EXIT, EXIT_VIA_TELEPORT, EXIT_OVERRIDE, ENDERPEARL, CHORUS_FRUIT_TELEPORT, TELEPORT, ITEM_PICKUP, ITEM_DROP, EXP_DROPS, INVINCIBLE, FALL_DAMAGE, FIREWORK_DAMAGE, GAMEMODE, TIME_LOCK, WEATHER_LOCK, NATURAL_HEALTH_REGEN, NATURAL_HUNGER_DRAIN, BLOCKED_CMDS, ALLOWED_CMDS, PISTONS, POTION_SPLASH
}
